# DeepLabV3 训练配置
model:
  name: deeplabv3
  n_channels: 1
  n_classes: 3
  backbone: resnet50
  pretrained: true
  bilinear: true
  weights:
    - 0.96275112
    - 0.8969029
    - 0.14034598
  checkpoint: null
  device: cpu
dataset:
  name: battery_2
  path: /workspaces/paser/data/battery_2
  train_images_dir: train_images
  train_labels_dir: train_label
  val_images_dir: validation_images
  val_labels_dir: validation_label
  test_images_dir: test_images
  test_labels_dir: test_label
batch_size: 32
shuffle: true
pin_memory: true
optimizer:
  name: adam
  learning_rate: 0.001
  weight_decay: 0.0
epochs: 1
checkpoint_save_interval: 5
compute_metrics_interval: 2
train_metrics_compute_interval: 1
save_best_checkpoint_val: true
wandb:
  project: paser_deeplabv3
  group: default
  name: deeplabv3_run
  mode: disabled
save_code_snapshot: false
noisy_dataset: false
model_type: basic  # 可选值: basic, global_distill
device: cpu
